/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Admin
 */
public class NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form NhanVien
     */
    public NhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QL_NhanVien = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        CapNhat = new javax.swing.JPanel();
        txtNV_MaNV = new javax.swing.JTextField();
        txtNV_SDT = new javax.swing.JTextField();
        txtNV_HoTen = new javax.swing.JTextField();
        rdoNV_NhanVien = new javax.swing.JRadioButton();
        rdoNV_ChuTro = new javax.swing.JRadioButton();
        lblNV_Last = new javax.swing.JLabel();
        lblNV_First = new javax.swing.JLabel();
        lblNV_Previous = new javax.swing.JLabel();
        lblNV_Next = new javax.swing.JLabel();
        btnNV_Them = new javax.swing.JButton();
        btnNV_Sua = new javax.swing.JButton();
        btnNV_Xoa = new javax.swing.JButton();
        btnNV_Moi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DanhSach = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        Title = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QL_NhanVien.setBackground(new java.awt.Color(255, 255, 255));

        CapNhat.setBackground(new java.awt.Color(255, 255, 255));
        CapNhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CapNhat.add(txtNV_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 46, 403, -1));
        CapNhat.add(txtNV_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 170, 403, -1));
        CapNhat.add(txtNV_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 108, 403, -1));

        rdoNV_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNV_NhanVien.setText("Nhan vien");
        CapNhat.add(rdoNV_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 238, -1, -1));

        rdoNV_ChuTro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNV_ChuTro.setText("Chu tro");
        CapNhat.add(rdoNV_ChuTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 238, -1, -1));

        lblNV_Last.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNV_Last.setForeground(new java.awt.Color(0, 0, 0));
        lblNV_Last.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNV_Last.setText(">|");
        CapNhat.add(lblNV_Last, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 70, 30));

        lblNV_First.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNV_First.setForeground(new java.awt.Color(0, 0, 0));
        lblNV_First.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNV_First.setText("|<");
        CapNhat.add(lblNV_First, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 70, 30));

        lblNV_Previous.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNV_Previous.setForeground(new java.awt.Color(0, 0, 0));
        lblNV_Previous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNV_Previous.setText("<<");
        CapNhat.add(lblNV_Previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 70, 30));

        lblNV_Next.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNV_Next.setForeground(new java.awt.Color(0, 0, 0));
        lblNV_Next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNV_Next.setText(">>");
        CapNhat.add(lblNV_Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 70, 30));

        btnNV_Them.setText("Thêm");
        CapNhat.add(btnNV_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 70, 30));

        btnNV_Sua.setText("Sua");
        CapNhat.add(btnNV_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 70, 30));

        btnNV_Xoa.setText("Xoa");
        CapNhat.add(btnNV_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 70, 30));

        btnNV_Moi.setText("Moi");
        CapNhat.add(btnNV_Moi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 70, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ma nhan vien");
        CapNhat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ho va ten");
        CapNhat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 86, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("SÐT");
        CapNhat.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 148, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Chuc vu");
        CapNhat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 210, -1, -1));

        jTabbedPane1.addTab("Cap nhat", CapNhat);

        DanhSach.setBackground(new java.awt.Color(255, 255, 255));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma nhan vien", "Ho va ten", "SÐT", "Chuc vu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        javax.swing.GroupLayout DanhSachLayout = new javax.swing.GroupLayout(DanhSach);
        DanhSach.setLayout(DanhSachLayout);
        DanhSachLayout.setHorizontalGroup(
            DanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        DanhSachLayout.setVerticalGroup(
            DanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DanhSachLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sach", DanhSach);

        Title.setBackground(new java.awt.Color(42, 63, 84));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QL_NhanVienLayout = new javax.swing.GroupLayout(QL_NhanVien);
        QL_NhanVien.setLayout(QL_NhanVienLayout);
        QL_NhanVienLayout.setHorizontalGroup(
            QL_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        QL_NhanVienLayout.setVerticalGroup(
            QL_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QL_NhanVienLayout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QL_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QL_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CapNhat;
    private javax.swing.JPanel DanhSach;
    private javax.swing.JPanel QL_NhanVien;
    private javax.swing.JPanel Title;
    private javax.swing.JButton btnNV_Moi;
    private javax.swing.JButton btnNV_Sua;
    private javax.swing.JButton btnNV_Them;
    private javax.swing.JButton btnNV_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNV_First;
    private javax.swing.JLabel lblNV_Last;
    private javax.swing.JLabel lblNV_Next;
    private javax.swing.JLabel lblNV_Previous;
    private javax.swing.JRadioButton rdoNV_ChuTro;
    private javax.swing.JRadioButton rdoNV_NhanVien;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtNV_HoTen;
    private javax.swing.JTextField txtNV_MaNV;
    private javax.swing.JTextField txtNV_SDT;
    // End of variables declaration//GEN-END:variables
}
